pipeline {
    agent any

    environment {
        CI = 'true'
        NODE_OPTIONS = '--openssl-legacy-provider'
    }

    stages {

        stage('Build') {
            steps {
                echo "===== BUILD STAGE ====="
                sh 'rm -rf app || true'
                sh 'git clone -b react-app https://github.com/alysha10/a428-cicd-labs.git app'
                dir('app') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                echo "===== TEST STAGE ====="
                dir('app') {
                    sh 'chmod +x jenkins/scripts/*.sh'
                    sh './jenkins/scripts/test.sh || true'
                }
            }
        }

        stage('Manual Approval') {
            steps {
                echo "===== MANUAL APPROVAL STAGE ====="
                input message: 'Apakah ingin melanjutkan ke Deploy?', ok: 'Ya, Deploy!'
            }
        }

        stage('Deploy') {
            steps {
                echo "===== DEPLOY STAGE ====="
                sh '''
                echo "Menjalankan proses deploy..."

                rm -rf /var/www/html/* || true
                cp -r app/build/* /var/www/html/

                echo "Aplikasi berhasil dideploy."
                echo "Menunggu 1 menit sebelum pipeline selesai..."

                # Delay 1 menit sesuai kriteria
                sleep 60

                echo "1 menit selesai. Deploy stage selesai."
                '''
            }
        }
    }

    post {
        success {
            echo 'PIPELINE SUCCESS'
        }
        failure {
            echo 'PIPELINE FAILED'
        }
    }
}
